project:
  type: book
  resources:
    - CNAME
    - tlf/
    - slides/

book:
  title: "R for Clinical Study Reports and Submission"
  author:
    - Yilong Zhang
    - Nan Xiao
    - Keaven Anderson
    - Yalin Zhu
  description: |
    Learn how to prepare tables, listings, and figures for
    clinical study report and submit to regulatory agencies,
    the essential part of clinical trial development.

  output-file: "r4csr"

  cover-image: "assets/cover.png"
  image: "assets/preview.jpg"
  favicon: "assets/favicon.png"

  site-url: https://r4csr.org/
  repo-url: https://github.com/elong0527/r4csr
  repo-actions: [edit, issue, source]
  sharing: [twitter, linkedin]
  reader-mode: true

  open-graph:
    image: assets/preview.jpg
    description: |
      Learn how to prepare tables, listings, and figures for
      clinical study report and submit to regulatory agencies,
      the essential part of clinical trial development.
  twitter-card:
    image: assets/preview.jpg
    description: |
      Learn how to prepare tables, listings, and figures for
      clinical study report and submit to regulatory agencies,
      the essential part of clinical trial development.
    card-style: summary_large_image

  google-analytics: "G-MKYDL3PNW1"

  chapters:
    - index.qmd
    - preface.qmd

    - part: "Delivering TLFs in CSR"
      chapters:
        - tlf-overview.qmd
        - tlf-disposition.qmd
        - tlf-population.qmd
        - tlf-baseline.qmd
        - tlf-efficacy-ancova.qmd
        - tlf-efficacy-km.qmd
        - tlf-ae-summary.qmd
        - tlf-ae-specific.qmd
        - tlf-assemble.qmd
    - part: "Clinical trial project"
      chapters:
        - project-overview.qmd
        - project-folder.qmd
        - project-management.qmd
    - part: "eCTD submission"
      chapters:
        - submission-overview.qmd
        - submission-package.qmd
        - submission-environment.qmd

    - references.qmd

bibliography: references.bib

format:
  html:
    theme: [cosmo, custom.scss]
    mainfont: "Invention, system-ui, -apple-system, Segoe UI, Roboto, Helvetica Neue, Noto Sans, Liberation Sans, Arial, sans-serif, Apple Color Emoji, Segoe UI Emoji, Segoe UI Symbol, Noto Color Emoji"
    code-link: true
  pdf:
    documentclass: tex/svmono
    include-in-header:
      - "tex/preamble.tex"
    include-before-body:
      - "tex/before_body.tex"
    include-after-body:
      - "tex/after_body.tex"
    cite-method: natbib
    keep-tex: true
    toc: true
